language: dart
dist: xenial
matrix:
  include:
    - name: Analyze
      env: COMMAND=analyze
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - cd $HOME
  - git clone https://github.com/flutter/flutter.git -b beta
  - $HOME/flutter/bin/flutter doctor
script:
  - echo 'API_URL=192.168.0.104:3000\n' >> .env
  - $HOME/flutter/bin/flutter $COMMAND
cache:
  directories:
    - $HOME/.pub-cache
