language: dart
dist: xenial
matrix:
  include:
    - name: Analyze
      env: COMMAND=analyze
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - pwd
  - cd $HOME
  - git clone https://github.com/flutter/flutter.git -b beta
  - $HOME/flutter/bin/flutter doctor
script:
  - ls
  - cd build/esron/systranca_app
  - $HOME/flutter/bin/flutter $COMMAND
cache:
  directories:
    - $HOME/.pub-cache
